version: '3.8'

services: 
  # 关联数据库服务器 milvus 1 不支持 MySQL 8.0 及其以上。
  mysql-server:
    image: mysql:5.7.33
    container_name: exert-milvus-mysql-server
    restart: always
    ports: 
      - 33061:3306
      - 33062:33060
    volumes: 
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/file/:/var/lib/mysql-files
      - ./mysql/conf/:/etc/mysql/:ro
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=exert
    networks: 
      - exert-milvus-net

  # 向量数据库服务器
  milvus-1-server:
    image: milvusdb/milvus:1.0.0-cpu-d030521-1ea92e
    container_name: exert-milvus-server
    depends_on: 
      - mysql-server
    restart: always
    ports: 
      - 19531:19530
      - 19121:19121
    volumes:
      - ./milvus/db:/var/lib/milvus/db
      - ./milvus/conf:/var/lib/milvus/conf
      - ./milvus/logs:/var/lib/milvus/logs
      - ./milvus/wal:/var/lib/milvus/wal
    networks: 
      - exert-milvus-net

  etcd:
    container_name: exert-milvus-etcd
    image: quay.io/coreos/etcd:latest
    restart: always
    command: etcd -listen-peer-urls=http://127.0.0.1:2380 -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls=http://127.0.0.1:2380 --listen-metrics-urls=http://127.0.0.1:2381 --initial-cluster default=http://127.0.0.1:2380
    healthcheck:
      test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://localhost:2381/health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks: 
      - exert-milvus-net
    
  minio:
    container_name: exert-milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks: 
      - exert-milvus-net

  standalone:
    container_name: exert-milvus-standalone
    image: milvusdb/milvus:v2.0.0-rc2-20210712-a8e5fd2
    restart: always
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    ports:
      - "19530:19530"
    depends_on:
      - "etcd"
      - "minio"
    networks: 
      - exert-milvus-net
  
  torchpyc:
    container_name: milvus-torchpyc
    build:
      context: ./torchpyc
      dockerfile: dockerfile
    restart: always
    environment: 
      - MILVUS_ADDRESS=standalone:19530
    volumes: 
      - ./torchpyc:/app
    ports: 
      - 9530:9530
    depends_on: 
      - standalone
    networks: 
      - exert-milvus-net

networks: 
  exert-milvus-net:
    name: exert-milvus-net
    driver: bridge
