FROM python:3.9.6-buster

VOLUME [ "/app" ]

COPY ./requirements.txt /requirements.txt

WORKDIR /app

RUN cp /usr/share/zoneinfo/PRC /etc/localtime && \
    pip3 install torch==1.9.0+cpu torchvision==0.10.0+cpu torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html && \
    pip3 install -r /requirements.txt

ENTRYPOINT [ "python", "app.py" ]
